name = "go2asia-auth-service"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
name = "go2asia-auth-service"

[env.staging]
name = "go2asia-auth-service-staging"

# Vars injected by CI/CD:
# ENVIRONMENT (e.g. "staging")
# VERSION (git sha)
#
# Secrets/bindings are configured in Cloudflare Dashboard for staging.



